package uiass.gisiba.eia.java.entity.inventory;

public enum ProductCatagory {

    LAPTOP, DESKTOP_PC, PHONE, PRINTER, TABLET, SMARTWATCH, MONITOR, KEYBOARD, MOUSE, HEADPHONES,  
    SPEAKER, CAMERA, GAMING_CONSOLE, ROUTER, MODEM, STORAGE_DEVICE, PROJECTOR, SCANNER, WEBCAM
    
}
